// Bundles the static site into a single Cloudflare Worker script
// (deploy/out/worker.js). Used because the deploy environment can't use
// Workers static-asset uploads; the site is small enough (~1.1 MB) to inline.
// Run: node deploy/build-worker.mjs && (cd deploy/out && npx wrangler deploy)
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";

const ROOT = path.resolve(new URL("..", import.meta.url).pathname);
const OUT = path.join(ROOT, "deploy/out");
mkdirSync(OUT, { recursive: true });

const FILES = {
  "/index.html": ["index.html", "text/html; charset=utf-8"],
  "/src/styles.css": ["src/styles.css", "text/css; charset=utf-8"],
  "/src/core.js": ["src/core.js", "text/javascript; charset=utf-8"],
  "/src/app.js": ["src/app.js", "text/javascript; charset=utf-8"],
  "/vendor/xlsx.full.min.js": ["vendor/xlsx.full.min.js", "text/javascript; charset=utf-8"],
  "/fixtures/sample-marks.xlsx": ["fixtures/sample-marks.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", true],
};

const entries = Object.entries(FILES).map(([route, [file, type, binary]]) => {
  const buf = readFileSync(path.join(ROOT, file));
  return `  ${JSON.stringify(route)}: { type: ${JSON.stringify(type)}, ${binary ? `b64: ${JSON.stringify(buf.toString("base64"))}` : `body: ${JSON.stringify(buf.toString("utf8"))}`} }`;
});

const CSP = [
  "default-src 'self'", "script-src 'self'", "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
  "font-src https://fonts.gstatic.com", "img-src 'self' data:", "connect-src 'self'",
  "object-src 'none'", "base-uri 'none'", "frame-ancestors 'none'", "form-action 'none'",
].join("; ");

writeFileSync(path.join(OUT, "worker.js"), `// Generated by deploy/build-worker.mjs — do not edit.
const FILES = {
${entries.join(",\n")}
};
const decode = (b64) => Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));
const HEADERS = {
  "x-content-type-options": "nosniff",
  "referrer-policy": "no-referrer",
  "x-frame-options": "DENY",
  "content-security-policy": ${JSON.stringify(CSP)},
};
export default {
  fetch(request) {
    const url = new URL(request.url);
    if (request.method !== "GET" && request.method !== "HEAD") return new Response("Method not allowed", { status: 405 });
    const f = FILES[url.pathname === "/" ? "/index.html" : url.pathname];
    if (!f) return new Response("Not found", { status: 404, headers: HEADERS });
    const html = f.type.startsWith("text/html");
    return new Response(request.method === "HEAD" ? null : f.b64 ? decode(f.b64) : f.body, {
      headers: { ...HEADERS, "content-type": f.type, "cache-control": html ? "no-cache" : "public, max-age=300" },
    });
  },
};
`);
writeFileSync(path.join(OUT, "wrangler.jsonc"), JSON.stringify({
  name: "grading-console", main: "worker.js", compatibility_date: "2026-09-26", workers_dev: true,
}, null, 2));
console.log("wrote", path.join(OUT, "worker.js"));
